services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - CLOUDFLARE_PUBLIC_URL=$CLOUDFLARE_PUBLIC_URL
      - CLOUDFLARE_ACCOUNT_ID=$CLOUDFLARE_ACCOUNT_ID
      - CLOUDFLARE_ACCESS_KEY_ID=$CLOUDFLARE_ACCESS_KEY_ID
      - CLOUDFLARE_SECRET_ACCESS_KEY=$CLOUDFLARE_SECRET_ACCESS_KEY
      - CLOUDFLARE_BUCKET=$CLOUDFLARE_BUCKET
      - DATABASE_URL=postgresql://DOCKER:DOCKER@pg:5432/url-shortener
    ports:
      - "$PORT:$PORT"
    depends_on:
      - pg
    restart: unless-stopped

  pg:
    image: bitnami/postgresql:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=DOCKER
      - POSTGRES_PASSWORD=DOCKER
      - POSTGRES_DB=url-shortener
    volumes:
      - "./docker:/docker-entrypoint-initdb.d"
